#!/bin/sh

IEEE_PATH="/sys/class/ieee80211"
THERMAL_PATH="/sys/class/thermal"

get_mtwifi_temp() {
	local flag
	local ifname
	local temp
	local mtwifi_vifs="ra0 rax0 rai0 ray0 rae0 raz0"
	local result=""

	for ifname in $mtwifi_vifs; do
		if [ -f "/sys/class/net/${ifname}/flags" ]; then
			flag="$(cat /sys/class/net/${ifname}/flags)"
			if [ "$((flag & 0x1))" -eq "1" ]; then
				temp="$(iwpriv ${ifname} stat | awk '/CurrentTemperature/ {printf("%d°C", $3)}')"
				[ -z "$result" ] && result="${temp}" || result="${result}/${temp}"
			fi
		fi
	done
	echo ${result:-unknown}
}

case "$DISTRIB_TARGET" in
ipq40xx/*|ipq806x/*)
	wifi_temp="$(awk '{printf("%.1f°C ", $0 / 1000)}' "$IEEE_PATH"/phy*/device/hwmon/hwmon*/temp1_input 2>"/dev/null" | awk '$1=$1')"
	;;
mediatek/mt7622)
	wifi_temp="$(awk '{printf("%.1f°C ", $0 / 1000)}' "$IEEE_PATH"/wl*/hwmon*/temp1_input 2>"/dev/null" | awk '$1=$1')"
	;;
mediatek/filogic)
	wifi_temp="$(get_mtwifi_temp)"
	;;
*)
	wifi_temp="$(awk '{printf("%.1f°C ", $0 / 1000)}' "$IEEE_PATH"/phy*/hwmon*/temp1_input 2>"/dev/null" | awk '$1=$1')"
	;;
esac

echo "${wifi_temp:-unknown}"
